# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a14f6e48a078b74560fdea26773cb3cc1cd4daa3fd420cb222b9c98b2386836b2c6e7d317f89a380893cad91dd6dc59a5886c29b9b65a9a8e14722b1bd892dc8

test:
  secret_key_base: 5dc8dda0974fd997fa30d327c9f6d2e76ac6155d2348270a5f8db16078e9480240c6820d1600b33ee60be1230b571a230cadce183a18815f473e6bb6784937c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
